"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-19 22:09:42.567672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_link',
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('discord_user_id', 'provider')
    )
    op.create_table('consent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_user_guild', 'consent', ['discord_user_id', 'guild_id'], unique=False)
    op.create_table('guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'key')
    )
    op.create_table('oauth_state',
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('document_provider', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_status', 'session', ['status'], unique=False)
    op.create_table('session_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_display_name', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'discord_user_id', name='uq_participant_per_session')
    )
    op.create_table('transcription_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('encryption_key_id', sa.Text(), nullable=False),
    sa.Column('wrapped_data_key', sa.LargeBinary(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'discord_user_id', name='uq_job_per_speaker')
    )
    op.create_index('ix_job_retention', 'transcription_job', ['retention_until'], unique=False)
    op.create_index('ix_job_status', 'transcription_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_status', table_name='transcription_job')
    op.drop_index('ix_job_retention', table_name='transcription_job')
    op.drop_table('transcription_job')
    op.drop_table('session_participant')
    op.drop_index('ix_session_status', table_name='session')
    op.drop_table('session')
    op.drop_table('oauth_state')
    op.drop_table('guild_config')
    op.drop_index('ix_consent_user_guild', table_name='consent')
    op.drop_table('consent')
    op.drop_table('account_link')
    # ### end Alembic commands ###
