apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sturnus.fullname" . }}-bot
  labels:
    {{- include "sturnus.componentLabels" (dict "root" . "component" "bot") | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.bot.persistence.accessMode }}
  {{- with .Values.bot.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.bot.persistence.size }}
